export const PAYMENT_STATES = {
  ISSUED: "ISSUED",
  PROOF_SUBMITTED: "PROOF_SUBMITTED",
  SOURCE_VERIFY_PENDING: "SOURCE_VERIFY_PENDING",
  SOURCE_VERIFIED: "SOURCE_VERIFIED",
  POLICY_EVALUATION_PENDING: "POLICY_EVALUATION_PENDING",
  POLICY_SATISFIED: "POLICY_SATISFIED",
  SETTLEMENT_REQUESTED: "SETTLEMENT_REQUESTED",
  SETTLEMENT_PENDING: "SETTLEMENT_PENDING",
  SETTLEMENT_CONFIRMED: "SETTLEMENT_CONFIRMED",
  RELEASED: "RELEASED",
  EXPIRED: "EXPIRED",
  SOURCE_VERIFY_FAILED: "SOURCE_VERIFY_FAILED",
  POLICY_FAILED: "POLICY_FAILED",
  SETTLEMENT_REJECTED: "SETTLEMENT_REJECTED",
  SETTLEMENT_FAILED_RETRYABLE: "SETTLEMENT_FAILED_RETRYABLE",
  SETTLEMENT_FAILED_FINAL: "SETTLEMENT_FAILED_FINAL",
  REPLAY_REJECTED: "REPLAY_REJECTED",
  CONTRACT_DRIFT_REJECTED: "CONTRACT_DRIFT_REJECTED",
} as const;

export type PaymentState =
  (typeof PAYMENT_STATES)[keyof typeof PAYMENT_STATES];

export const ACTIVE_PAYMENT_STATES = new Set<PaymentState>([
  PAYMENT_STATES.ISSUED,
  PAYMENT_STATES.PROOF_SUBMITTED,
  PAYMENT_STATES.SOURCE_VERIFY_PENDING,
  PAYMENT_STATES.SOURCE_VERIFIED,
  PAYMENT_STATES.POLICY_EVALUATION_PENDING,
  PAYMENT_STATES.POLICY_SATISFIED,
  PAYMENT_STATES.SETTLEMENT_REQUESTED,
  PAYMENT_STATES.SETTLEMENT_PENDING,
  PAYMENT_STATES.SETTLEMENT_CONFIRMED,
]);

export const TERMINAL_PAYMENT_STATES = new Set<PaymentState>([
  PAYMENT_STATES.RELEASED,
  PAYMENT_STATES.EXPIRED,
  PAYMENT_STATES.POLICY_FAILED,
  PAYMENT_STATES.SETTLEMENT_REJECTED,
  PAYMENT_STATES.SETTLEMENT_FAILED_FINAL,
  PAYMENT_STATES.REPLAY_REJECTED,
  PAYMENT_STATES.CONTRACT_DRIFT_REJECTED,
]);

export const FAILURE_PAYMENT_STATES = new Set<PaymentState>([
  PAYMENT_STATES.EXPIRED,
  PAYMENT_STATES.SOURCE_VERIFY_FAILED,
  PAYMENT_STATES.POLICY_FAILED,
  PAYMENT_STATES.SETTLEMENT_REJECTED,
  PAYMENT_STATES.SETTLEMENT_FAILED_RETRYABLE,
  PAYMENT_STATES.SETTLEMENT_FAILED_FINAL,
  PAYMENT_STATES.REPLAY_REJECTED,
  PAYMENT_STATES.CONTRACT_DRIFT_REJECTED,
]);

export function isPaymentState(value: string): value is PaymentState {
  return Object.values(PAYMENT_STATES).includes(value as PaymentState);
}

export function isActivePaymentState(state: PaymentState): boolean {
  return ACTIVE_PAYMENT_STATES.has(state);
}

export function isTerminalPaymentState(state: PaymentState): boolean {
  return TERMINAL_PAYMENT_STATES.has(state);
}

export function isFailurePaymentState(state: PaymentState): boolean {
  return FAILURE_PAYMENT_STATES.has(state);
}
