import { PAYMENT_STATES, type PaymentState } from "./payment-state";

export type PaymentTransitionMap = Record<PaymentState, ReadonlySet<PaymentState>>;

/**
 * Canonical Gateway-owned transition map.
 *
 * This is intentionally strict:
 * - only explicitly allowed transitions may occur
 * - terminal states do not transition back into active flow
 * - retries from retryable settlement failure go back to SETTLEMENT_REQUESTED
 */
export const PAYMENT_TRANSITIONS: PaymentTransitionMap = {
  [PAYMENT_STATES.ISSUED]: new Set<PaymentState>([
    PAYMENT_STATES.PROOF_SUBMITTED,
    PAYMENT_STATES.EXPIRED,
  ]),

  [PAYMENT_STATES.PROOF_SUBMITTED]: new Set<PaymentState>([
    PAYMENT_STATES.SOURCE_VERIFY_PENDING,
    PAYMENT_STATES.SOURCE_VERIFY_FAILED,
    PAYMENT_STATES.REPLAY_REJECTED,
    PAYMENT_STATES.CONTRACT_DRIFT_REJECTED,
    PAYMENT_STATES.EXPIRED,
  ]),

  [PAYMENT_STATES.SOURCE_VERIFY_PENDING]: new Set<PaymentState>([
    PAYMENT_STATES.SOURCE_VERIFIED,
    PAYMENT_STATES.SOURCE_VERIFY_FAILED,
    PAYMENT_STATES.REPLAY_REJECTED,
    PAYMENT_STATES.CONTRACT_DRIFT_REJECTED,
    PAYMENT_STATES.EXPIRED,
  ]),

  [PAYMENT_STATES.SOURCE_VERIFIED]: new Set<PaymentState>([
    PAYMENT_STATES.POLICY_EVALUATION_PENDING,
    PAYMENT_STATES.POLICY_SATISFIED,
    PAYMENT_STATES.REPLAY_REJECTED,
    PAYMENT_STATES.CONTRACT_DRIFT_REJECTED,
    PAYMENT_STATES.EXPIRED,
  ]),

  [PAYMENT_STATES.POLICY_EVALUATION_PENDING]: new Set<PaymentState>([
    PAYMENT_STATES.POLICY_SATISFIED,
    PAYMENT_STATES.POLICY_FAILED,
    PAYMENT_STATES.EXPIRED,
  ]),

  [PAYMENT_STATES.POLICY_SATISFIED]: new Set<PaymentState>([
    PAYMENT_STATES.SETTLEMENT_REQUESTED,
    PAYMENT_STATES.SETTLEMENT_REJECTED,
    PAYMENT_STATES.EXPIRED,
  ]),

  [PAYMENT_STATES.SETTLEMENT_REQUESTED]: new Set<PaymentState>([
    PAYMENT_STATES.SETTLEMENT_PENDING,
    PAYMENT_STATES.SETTLEMENT_REJECTED,
    PAYMENT_STATES.EXPIRED,
  ]),

  [PAYMENT_STATES.SETTLEMENT_PENDING]: new Set<PaymentState>([
    PAYMENT_STATES.SETTLEMENT_CONFIRMED,
    PAYMENT_STATES.SETTLEMENT_FAILED_RETRYABLE,
    PAYMENT_STATES.SETTLEMENT_FAILED_FINAL,
    PAYMENT_STATES.REPLAY_REJECTED,
    PAYMENT_STATES.CONTRACT_DRIFT_REJECTED,
    PAYMENT_STATES.EXPIRED,
  ]),

  [PAYMENT_STATES.SETTLEMENT_CONFIRMED]: new Set<PaymentState>([
    PAYMENT_STATES.RELEASED,
  ]),

  [PAYMENT_STATES.RELEASED]: new Set<PaymentState>([]),

  [PAYMENT_STATES.EXPIRED]: new Set<PaymentState>([]),

  [PAYMENT_STATES.SOURCE_VERIFY_FAILED]: new Set<PaymentState>([]),

  [PAYMENT_STATES.POLICY_FAILED]: new Set<PaymentState>([]),

  [PAYMENT_STATES.SETTLEMENT_REJECTED]: new Set<PaymentState>([]),

  [PAYMENT_STATES.SETTLEMENT_FAILED_RETRYABLE]: new Set<PaymentState>([
    PAYMENT_STATES.SETTLEMENT_REQUESTED,
  ]),

  [PAYMENT_STATES.SETTLEMENT_FAILED_FINAL]: new Set<PaymentState>([]),

  [PAYMENT_STATES.REPLAY_REJECTED]: new Set<PaymentState>([]),

  [PAYMENT_STATES.CONTRACT_DRIFT_REJECTED]: new Set<PaymentState>([]),
};

export function getAllowedTransitions(from: PaymentState): ReadonlySet<PaymentState> {
  return PAYMENT_TRANSITIONS[from];
}
